### ISSUE TITLE
SubmitPayForBlob wrong param count

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/docs#781]
I'm on arabica-8 with

```
$ celestia version
Semantic version: v0.11.0-rc1
Commit: b62452af1e7dd1cc1b9a5ca1d96d1545154b4d04
Build Date: Thu Jun  1 11:22:57 EDT 2023
System version: arm64/darwin
Golang version: go1.20.4
```

## Problem

```
$ celestia rpc state SubmitPayForBlob 0x1874e642f5dde589 '"Hello there!!"' 2000 100000
{"jsonrpc":"2.0","id":1,"error":{"code":-32602,"message":"wrong param count (method 'state.SubmitPayForBlob'): 4 != 3"}}
```
I copied this command from https://docs.celestia.org/developers/rpc-tutorial/#examples

**Comment by rootulp** [comment]
If I remove one of the params, I hit a panic

```
$ celestia rpc state SubmitPayForBlob 0x1874e642f5dde589 '"Hello there!!"'  100000
panic: runtime error: index out of range [3] with length 3

goroutine 1 [running]:
main.parseParams({0x16f55759b, 0x10}, {0x140005213d0, 0x3, 0x0?})
	/Users/rootulp/git/rootulp/celestia/celestia-node/cmd/celestia/rpc.go:142 +0x1408
main.glob..func5(0x104cdc2c0?, {0x140005213b0?, 0x5?, 0x5?})
	/Users/rootulp/git/rootulp/celestia/celestia-node/cmd/celestia/rpc.go:83 +0x70
github.com/spf13/cobra.(*Command).execute(0x104cdc2c0, {0x14000521360, 0x5, 0x5})
	/Users/rootulp/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x5b0
github.com/spf13/cobra.(*Command).ExecuteC(0x104cdbfe0)
	/Users/rootulp/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/rootulp/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/Users/rootulp/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:961
main.run()
	/Users/rootulp/git/rootulp/celestia/celestia-node/cmd/celestia/main.go:28 +0x64
main.main()
	/Users/rootulp/git/rootulp/celestia/celestia-node/cmd/celestia/main.go:21 +0x1c
```
